services:

  db:
    image: mysql:8.0
    container_name: univault_db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: univault

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: univault_phpmyadmin
    restart: always

    ports:
      - "8080:80"

    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

    depends_on:
      - db


volumes:
  db_data: